name: dev CI
on:
  push:
    branches: "**" # [ "main" ]
  #   paths-ignore:
  #     - '**/*.md'
  #     - '**/*.txt'
  workflow_dispatch:   

jobs:
  buildjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Necessary to access local action
      - name: dev-build
        uses: ./.github/workflows/java-build.yaml
        #secrets: inherit #https://docs.github.com
    
  
