name: dev CI
on:
  push:
    branches: "**" # [ "main" ]
  #   paths-ignore:
  #     - '**/*.md'
  #     - '**/*.txt'
  workflow_dispatch:   

jobs:
  buildjob:
    uses: ./.github/workflows/java-build.yaml
    #secrets: inherit #https://docs.github.com
    
  
