name: dev CI
on:
  push:
    branches: "**" # [ "main" ]
  #   paths-ignore:
  #     - '**/*.md'
  #     - '**/*.txt'
  workflow_dispatch:   

jobs:
  buildjob:
    runs-on: ubuntu-latest
    - name: dev-build
    - uses: ./.github/workflows/java-build.yaml
        #secrets: inherit #https://docs.github.com
    
  
