name: java build pipeline
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    #runner configs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        #Compile
      - name: Build with Maven
        run: mvn clean package -B -Dmaven.test.skip
      - run: mkdir candidate-binary && cp target/*.jar candidate-binary
